"""Evidence Provenance UI Semantics — Task 5.5.

Defines the visual treatment contracts for provenance badges,
confidence indicators, null-state display, and AI disclosure.
These are data contracts consumed by frontend components.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class ProvBadgeConfig:
    """Visual treatment config for a provenance badge."""
    layer: str  # source | enrichment | canonical | authority
    label: str
    color_token: str  # CSS custom property name
    icon: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "layer": self.layer,
            "label": self.label,
            "color_token": self.color_token,
            "icon": self.icon,
        }


# Provenance badge definitions
PROV_BADGES: dict[str, ProvBadgeConfig] = {
    "source": ProvBadgeConfig(
        layer="source",
        label="Source",
        color_token="--ukip-muted",
        icon="upload",
    ),
    "enrichment": ProvBadgeConfig(
        layer="enrichment",
        label="Enriched",
        color_token="--ukip-cyan",
        icon="sparkles",
    ),
    "canonical": ProvBadgeConfig(
        layer="canonical",
        label="Canonical",
        color_token="--ukip-emerald",
        icon="check-circle",
    ),
    "authority": ProvBadgeConfig(
        layer="authority",
        label="Authority",
        color_token="--ukip-violet",
        icon="shield-check",
    ),
}


@dataclass
class ConfidenceConfig:
    """Visual config for a confidence level."""
    level: str  # high | medium | low | unknown | review_required
    label: str
    color_token: str
    min_threshold: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "level": self.level,
            "label": self.label,
            "color_token": self.color_token,
            "min_threshold": self.min_threshold,
        }


CONFIDENCE_LEVELS: list[ConfidenceConfig] = [
    ConfidenceConfig("high", "High confidence", "--ukip-emerald", 0.8),
    ConfidenceConfig("medium", "Medium confidence", "--ukip-warning", 0.5),
    ConfidenceConfig("low", "Low confidence", "--ukip-danger", 0.2),
    ConfidenceConfig("unknown", "Unknown", "--ukip-muted", 0.0),
    ConfidenceConfig("review_required", "Review required", "--ukip-warning", 0.0),
]


def get_confidence_level(score: float, requires_review: bool = False) -> ConfidenceConfig:
    """Get the confidence config for a given score."""
    if requires_review:
        return CONFIDENCE_LEVELS[4]  # review_required
    if score >= 0.8:
        return CONFIDENCE_LEVELS[0]
    if score >= 0.5:
        return CONFIDENCE_LEVELS[1]
    if score >= 0.2:
        return CONFIDENCE_LEVELS[2]
    return CONFIDENCE_LEVELS[3]


@dataclass
class NullStateConfig:
    """Visual config for null/empty field states."""
    style: str  # de_emphasized | hidden | placeholder
    opacity: float = 0.5
    show_reason: bool = True


# Null state: fields with no value are de-emphasized, not hidden
NULL_STATE = NullStateConfig(style="de_emphasized", opacity=0.5, show_reason=True)


@dataclass
class AIDisclosureConfig:
    """Config for AI-assisted/AI-generated disclosure."""
    badge_label: str
    color_token: str
    icon: str
    tooltip: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "badge_label": self.badge_label,
            "color_token": self.color_token,
            "icon": self.icon,
            "tooltip": self.tooltip,
        }


AI_ASSISTED = AIDisclosureConfig(
    badge_label="AI-assisted",
    color_token="--ukip-cyan",
    icon="cpu",
    tooltip="This content was produced with AI assistance. Verify against source data.",
)

AI_GENERATED = AIDisclosureConfig(
    badge_label="AI-generated",
    color_token="--ukip-cyan",
    icon="bot",
    tooltip="This content was generated by AI. Human review recommended.",
)


def get_prov_badge(layer: str) -> ProvBadgeConfig | None:
    """Get provenance badge config for a layer."""
    return PROV_BADGES.get(layer)


def get_ai_disclosure(is_generated: bool = False) -> AIDisclosureConfig:
    """Get appropriate AI disclosure config."""
    return AI_GENERATED if is_generated else AI_ASSISTED
