"use client";

/**
 * AIDisclosureBadge — Mandatory AI disclosure indicator.
 * Per GenAI governance contract, all AI outputs must display this badge.
 */

interface AIDisclosureBadgeProps {
  type: "assisted" | "generated";
  size?: "sm" | "md";
  className?: string;
}

const CONFIG = {
  assisted: {
    label: "AI-assisted",
    icon: "⚙",
    tooltip: "This content was produced with AI assistance. Verify against source data.",
  },
  generated: {
    label: "AI-generated",
    icon: "🤖",
    tooltip: "This content was generated by AI. Human review recommended.",
  },
};

export default function AIDisclosureBadge({
  type,
  size = "sm",
  className = "",
}: AIDisclosureBadgeProps) {
  const config = CONFIG[type];

  const sizeClasses =
    size === "sm"
      ? "px-1.5 py-0.5 text-[10px] gap-1"
      : "px-2 py-1 text-xs gap-1.5";

  return (
    <span
      className={`inline-flex items-center font-medium rounded border bg-cyan-50 dark:bg-cyan-500/10 text-cyan-700 dark:text-cyan-400 border-cyan-300 dark:border-cyan-500/30 ${sizeClasses} ${className}`}
      title={config.tooltip}
    >
      <span aria-hidden="true">{config.icon}</span>
      {config.label}
    </span>
  );
}
