"""Regression tests for entity deletion — issue #216.

Deleting an entity that had any `entity_relationships` row returned 500 from
both `DELETE /entities/{id}` and `DELETE /entities/bulk`. Two FKs referenced
`raw_entities` with no `ondelete`, and `models.py` declares no `relationship()`
anywhere, so there was no cascade at either the database or the ORM layer.

In production this is not an edge case: auto-resolve-on-ingest and the semantic
keyword engine write relationship rows within seconds of an import, so imported
entities became undeletable almost immediately.

The two references are deliberately not treated alike:

* `entity_relationships` CASCADEs — derived graph edges, regenerated by the
  engines that wrote them, nothing is lost.
* `harmonization_change_records` gets SET NULL — it is audit history recording
  who changed which field from what to what. Cascading it would mean deleting an
  entity silently destroys the evidence that someone edited it, and deleting the
  entity is exactly what someone covering their tracks would do.

WHY THESE TESTS ENABLE A PRAGMA: SQLite does not enforce foreign keys unless
`PRAGMA foreign_keys=ON`, and this suite leaves it off. Without it these tests
would pass against the unfixed code — the constraint would never be evaluated,
the delete would succeed, and the gate would be worthless. That gap is also the
reason #216 reached production: Postgres enforces the FK, the test database did
not. Teardown restores the default OFF, because conftest uses StaticPool and the
pragma would otherwise leak into every later test.
"""

from __future__ import annotations

import pytest
from sqlalchemy import text

from backend import models
from backend.database import SessionLocal

pytestmark = pytest.mark.postgres


@pytest.fixture
def fk_db():
    s = SessionLocal()
    # The pragma is a SQLite workaround, so only SQLite gets it: PostgreSQL
    # enforces foreign keys natively and rejects `PRAGMA` as a syntax error.
    is_sqlite = s.bind.dialect.name == "sqlite"
    if is_sqlite:
        s.execute(text("PRAGMA foreign_keys=ON"))
    try:
        yield s
    finally:
        s.rollback()
        try:
            s.execute(text("DELETE FROM harmonization_change_records"))
            s.execute(text("DELETE FROM entity_relationships"))
            s.execute(text("DELETE FROM raw_entities"))
            s.commit()
        except Exception:
            s.rollback()
        if is_sqlite:
            s.execute(text("PRAGMA foreign_keys=OFF"))
            s.commit()
        s.close()


def _entity(db, label: str) -> models.RawEntity:
    e = models.RawEntity(primary_label=label, domain="science", source="test")
    db.add(e)
    db.commit()
    db.refresh(e)
    return e


# ── The pragma itself ────────────────────────────────────────────────────────


def test_foreign_keys_are_actually_enforced(fk_db):
    """Guard the guard. If this fails, every assertion below is vacuous and the
    suite is silently not testing foreign keys at all."""
    if fk_db.bind.dialect.name != "sqlite":
        # PostgreSQL enforces foreign keys unconditionally; there is no switch
        # to read back, and nothing to guard against.
        pytest.skip("foreign keys are always enforced on this dialect")
    result = fk_db.execute(text("PRAGMA foreign_keys")).scalar()
    assert result == 1, "FK enforcement is off — the cascade assertions prove nothing"


# ── entity_relationships: cascade ────────────────────────────────────────────


class TestRelationshipsCascade:
    def test_entity_with_relationships_can_be_deleted(self, fk_db):
        a = _entity(fk_db, "source entity")
        b = _entity(fk_db, "target entity")
        fk_db.add(models.EntityRelationship(source_id=a.id, target_id=b.id, relation_type="related-to"))
        fk_db.commit()

        fk_db.delete(a)
        fk_db.commit()  # unfixed: IntegrityError, FK violation

        assert fk_db.get(models.RawEntity, a.id) is None

    def test_edges_are_removed_with_the_entity(self, fk_db):
        a = _entity(fk_db, "a")
        b = _entity(fk_db, "b")
        fk_db.add(models.EntityRelationship(source_id=a.id, target_id=b.id, relation_type="cites"))
        fk_db.commit()

        fk_db.delete(a)
        fk_db.commit()

        remaining = fk_db.query(models.EntityRelationship).filter(
            (models.EntityRelationship.source_id == a.id)
            | (models.EntityRelationship.target_id == a.id)
        ).count()
        assert remaining == 0

    def test_cascade_applies_to_the_target_side_too(self, fk_db):
        """`target_id` is a separate FK; fixing only `source_id` would leave an
        entity undeletable whenever something else points at it."""
        a = _entity(fk_db, "a")
        b = _entity(fk_db, "b")
        fk_db.add(models.EntityRelationship(source_id=a.id, target_id=b.id, relation_type="cites"))
        fk_db.commit()

        fk_db.delete(b)
        fk_db.commit()

        assert fk_db.get(models.RawEntity, b.id) is None


# ── harmonization_change_records: audit survives ─────────────────────────────


class TestAuditHistorySurvives:
    def test_entity_with_change_record_can_be_deleted(self, fk_db):
        e = _entity(fk_db, "edited entity")
        fk_db.add(models.HarmonizationChangeRecord(
            log_id=None, record_id=e.id, field="primary_label",
            old_value="before", new_value="after",
        ))
        fk_db.commit()

        fk_db.delete(e)
        fk_db.commit()

        assert fk_db.get(models.RawEntity, e.id) is None

    def test_change_record_survives_with_a_null_reference(self, fk_db):
        e = _entity(fk_db, "edited entity")
        fk_db.add(models.HarmonizationChangeRecord(
            log_id=None, record_id=e.id, field="primary_label",
            old_value="before", new_value="after",
        ))
        fk_db.commit()
        fk_db.delete(e)
        fk_db.commit()

        records = fk_db.query(models.HarmonizationChangeRecord).all()
        assert len(records) == 1, "audit history must outlive the entity it describes"
        assert records[0].record_id is None
        assert records[0].old_value == "before"
        assert records[0].new_value == "after"
