"""The localized-document boundary itself (#292), not any one section's copy.

`test_report_render_boundary.py` walks every real report a fixture can produce
and fails on any surface-prefixed string that leaked through. That is the
outcome guard. This is the structural one: it targets the seam directly —
`LocalizedReportDocument` should be unconstructible with a raw key in it, and
every renderer/exporter entry point must refuse to render a payload that
skipped `localize_section`/`localize_document`, rather than resolving keys
itself. A production renderer bypassing the boundary (reading `section.title`
straight off a collector, an exporter inventing its own `translate()` call)
would not necessarily leak a *visible* key — a mistranslated fallback or an
accidental literal could still read as plausible English — so this test does
not rely on scanning rendered text; it asserts the type-level refusal exists
and fires on the exact input a bypass would produce.
"""
from __future__ import annotations

import pytest

from backend.reporting.document import LocalizedReportDocument, ReportDocument, SectionError
from backend.reporting.excel_renderer import render_excel
from backend.reporting.html_renderer import render_html, render_html_document
from backend.reporting.localize import (
    UnresolvedCatalogKeyError,
    assert_localized_document,
    assert_localized_section,
    localize_document,
    with_params,
)
from backend.reporting.pptx_renderer import render_pptx
from backend.reporting.section_data import SectionData

pytestmark = pytest.mark.reporting


def _raw_section(**overrides) -> SectionData:
    base = dict(
        key="entity_stats",
        title="report.section.entity_stats",  # never resolved
        takeaway="30 of 40 entities pass validation.",
        method="Counts are scoped to this domain.",
    )
    base.update(overrides)
    return SectionData(**base)


def _raw_document(**overrides) -> ReportDocument:
    base = dict(
        domain_id="default",
        domain_name="default",
        title=with_params("report.cover.title", domain="default"),
        generated_at="2026-01-01 00:00 UTC",
        stakeholder_label="report.stakeholder.leadership.label",
        sections=(_raw_section(),),
    )
    base.update(overrides)
    return ReportDocument(**base)


#: Every field `LocalizedReportDocument` requires besides `sections` — kept in
#: one place so a field added to the type only needs updating here, not at
#: every construction site in this file.
def _localized_document(**overrides) -> LocalizedReportDocument:
    base = dict(
        language="en",
        domain_id="default",
        domain_name="default",
        title="Cover title",
        generated_at="2026-01-01 00:00 UTC",
        stakeholder_label="Leadership",
        domain_caption="Domain",
        generated_caption="Generated",
        stakeholder_lens_caption="Stakeholder lens",
        executive_summary_title="Executive Summary",
        manual_note_default_title="Analyst Note",
        generated_by_caption="Generated by UKIP",
        section_error_prefix="Error building section:",
        disclosure=None,
        sections=(),
    )
    base.update(overrides)
    return LocalizedReportDocument(**base)


class TestLocalizeDocumentProducesACleanBoundary:
    def test_every_owned_string_resolves(self):
        doc = localize_document(_raw_document(), "en")
        # Would raise if anything survived — this is the assertion, not just a
        # setup step, since localize_document already calls it internally.
        assert_localized_document(doc)

    def test_the_result_is_the_boundary_type(self):
        doc = localize_document(_raw_document(), "en")
        assert isinstance(doc, LocalizedReportDocument)


class TestTheGuardCatchesEveryBypassShape:
    """Each case starves the guard of the one thing localize_document would
    have provided, so a renderer/exporter that skipped it hits this exact
    failure rather than shipping a key silently.
    """

    def test_an_unlocalized_section_fails_its_own_assertion(self):
        with pytest.raises(UnresolvedCatalogKeyError):
            assert_localized_section(_raw_section())

    def test_a_key_buried_in_a_table_cell_fails(self):
        from backend.reporting.section_data import Table

        section = _raw_section(
            title="Entity Statistics",
            blocks=(Table(columns=("Status",), rows=(("report.status.passed",),)),),
        )
        with pytest.raises(UnresolvedCatalogKeyError):
            assert_localized_section(section)

    def test_html_render_html_refuses_a_raw_section(self):
        with pytest.raises(UnresolvedCatalogKeyError):
            render_html(_raw_section())

    def test_excel_render_excel_refuses_a_raw_section(self):
        import openpyxl

        with pytest.raises(UnresolvedCatalogKeyError):
            render_excel(_raw_section(), openpyxl.Workbook())

    def test_pptx_render_pptx_refuses_a_raw_section(self):
        from pptx import Presentation
        from pptx.dml.color import RGBColor

        with pytest.raises(UnresolvedCatalogKeyError):
            render_pptx(_raw_section(), Presentation(), RGBColor(0x63, 0x66, 0xF1))

    def test_a_smuggled_document_level_key_fails_document_assembly(self):
        """Not just a section field: a bypass could also hand-construct the
        document-level scalars (title, captions, …) without localizing them.
        """
        with pytest.raises(UnresolvedCatalogKeyError):
            assert_localized_document(
                _localized_document(title="report.cover.title")  # smuggled in unresolved
            )

    def test_a_smuggled_section_error_title_fails_document_assembly(self):
        """A `SectionError`'s title is deferred owned copy too, like any
        section's — a bypass constructing one directly, outside
        `localize_document()`, must be caught the same way.
        """
        with pytest.raises(UnresolvedCatalogKeyError):
            assert_localized_document(
                _localized_document(
                    sections=(
                        SectionError(
                            section_key="entity_stats",
                            title="report.section.entity_stats",  # never resolved
                            detail="boom",
                        ),
                    )
                )
            )

    def test_html_render_html_document_refuses_a_smuggled_document(self):
        with pytest.raises(UnresolvedCatalogKeyError):
            render_html_document(
                _localized_document(sections=(_raw_section(),))  # title is still a raw key
            )


class TestFooterAndErrorCopyCrossTheBoundary:
    """#292 review: the footer caption and a failed section's error label
    used to be literals `render_html_document` wrote itself, after the
    boundary — the same shape of violation the boundary exists to close for
    section content. Both now arrive pre-resolved on the document, like every
    other document-level caption.
    """

    def test_the_footer_and_error_label_come_from_the_document_not_a_literal(self):
        doc = _localized_document(
            generated_by_caption="SENTINEL-FOOTER-CAPTION",
            section_error_prefix="SENTINEL-ERROR-PREFIX",
            sections=(
                SectionError(section_key="k", title="Section K", detail="boom"),
            ),
        )

        html = render_html_document(doc)

        assert "SENTINEL-FOOTER-CAPTION" in html
        assert "SENTINEL-ERROR-PREFIX" in html
        # If either were still a hardcoded literal, swapping the document's
        # caption for a sentinel (above) would have had no effect and these
        # would still be present.
        assert "Generated by UKIP" not in html
        assert "Error building section:" not in html

    def test_the_exception_detail_itself_is_never_translated(self):
        """`SectionError.detail` is diagnostic, not owned copy — only the
        prefix in front of it is localized."""
        doc = _localized_document(
            sections=(
                SectionError(section_key="k", title="Section K", detail="ValueError: boom"),
            ),
        )

        html = render_html_document(doc)

        assert "ValueError: boom" in html


class TestSectionOrderIsPreserved:
    """#292 review: a failed section used to move to the end of the document
    regardless of where it was requested. `ReportDocument.sections` holds
    `SectionData` and `SectionError` in one sequence specifically so this
    cannot happen — see that field's docstring.
    """

    def test_a_failed_section_renders_between_its_successful_neighbours(self, db_session, monkeypatch):
        from backend import report_builder

        def _boom(db, domain_id, org_id):
            raise RuntimeError("synthetic collector failure")

        # entity_stats and harmonization_log both succeed; enrichment_coverage,
        # requested between them, fails — so its error must render between
        # their two sections, not after both.
        monkeypatch.setitem(report_builder.SECTION_COLLECTORS, "enrichment_coverage", _boom)

        doc = report_builder.assemble_report_document(
            db_session, "default",
            ["entity_stats", "enrichment_coverage", "harmonization_log"],
        )
        localized = localize_document(doc, "en")
        html = render_html_document(localized)

        entity_pos = html.index("Entity Statistics")
        error_pos = html.index(localized.section_error_prefix)
        harmonization_pos = html.index("Harmonization Log")

        assert entity_pos < error_pos < harmonization_pos, (
            "the failed section did not render between its requested neighbours: "
            f"entity={entity_pos} error={error_pos} harmonization={harmonization_pos}"
        )

    def test_the_document_sections_sequence_itself_preserves_the_slot(self, db_session, monkeypatch):
        """Same property, asserted directly on the aggregate rather than
        through rendered HTML — the two are independent proofs of the same
        invariant."""
        from backend import report_builder

        def _boom(db, domain_id, org_id):
            raise RuntimeError("synthetic collector failure")

        monkeypatch.setitem(report_builder.SECTION_COLLECTORS, "enrichment_coverage", _boom)

        doc = report_builder.assemble_report_document(
            db_session, "default",
            ["entity_stats", "enrichment_coverage", "harmonization_log"],
        )

        # sections[0] is always the stakeholder reading (assembled ahead of
        # the requested list); the requested three follow in order.
        kinds = [
            (s.key, "data") if isinstance(s, SectionData) else (s.section_key, "error")
            for s in doc.sections[1:]
        ]
        assert kinds == [
            ("entity_stats", "data"),
            ("enrichment_coverage", "error"),
            ("harmonization_log", "data"),
        ]
