import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import React from "react";
import ProvBadge from "../app/components/ProvBadge";
import ConfidenceIndicator from "../app/components/ConfidenceIndicator";
import AIDisclosureBadge from "../app/components/AIDisclosureBadge";
import ProvenanceFieldSection from "../app/components/ProvenanceFieldSection";

describe("ProvBadge", () => {
  it("renders source badge", () => {
    render(<ProvBadge layer="source" />);
    expect(screen.getByText("Source")).toBeTruthy();
  });

  it("renders enrichment badge", () => {
    render(<ProvBadge layer="enrichment" />);
    expect(screen.getByText("Enriched")).toBeTruthy();
  });

  it("renders canonical badge", () => {
    render(<ProvBadge layer="canonical" />);
    expect(screen.getByText("Canonical")).toBeTruthy();
  });

  it("renders authority badge", () => {
    render(<ProvBadge layer="authority" />);
    expect(screen.getByText("Authority")).toBeTruthy();
  });

  it("supports md size", () => {
    render(<ProvBadge layer="source" size="md" />);
    expect(screen.getByText("Source")).toBeTruthy();
  });
});

describe("ConfidenceIndicator", () => {
  it("renders high confidence", () => {
    render(<ConfidenceIndicator score={0.95} />);
    expect(screen.getByText("High")).toBeTruthy();
    expect(screen.getByText("(95%)")).toBeTruthy();
  });

  it("renders medium confidence", () => {
    render(<ConfidenceIndicator score={0.6} />);
    expect(screen.getByText("Medium")).toBeTruthy();
  });

  it("renders low confidence", () => {
    render(<ConfidenceIndicator score={0.3} />);
    expect(screen.getByText("Low")).toBeTruthy();
  });

  it("renders unknown for very low score", () => {
    render(<ConfidenceIndicator score={0.1} />);
    expect(screen.getByText("Unknown")).toBeTruthy();
  });

  it("renders review required when flagged", () => {
    render(<ConfidenceIndicator score={0.95} requiresReview />);
    expect(screen.getByText("Review required")).toBeTruthy();
  });

  it("hides score when showScore is false", () => {
    render(<ConfidenceIndicator score={0.9} showScore={false} />);
    expect(screen.getByText("High")).toBeTruthy();
    expect(screen.queryByText("(90%)")).toBeNull();
  });
});

describe("AIDisclosureBadge", () => {
  it("renders assisted badge", () => {
    render(<AIDisclosureBadge type="assisted" />);
    expect(screen.getByText("AI-assisted")).toBeTruthy();
  });

  it("renders generated badge", () => {
    render(<AIDisclosureBadge type="generated" />);
    expect(screen.getByText("AI-generated")).toBeTruthy();
  });

  it("has tooltip with disclosure text", () => {
    render(<AIDisclosureBadge type="generated" />);
    const badge = screen.getByText("AI-generated").closest("span");
    expect(badge?.getAttribute("title")).toContain("generated by AI");
  });
});

describe("ProvenanceFieldSection", () => {
  it("renders section with badge and children", () => {
    render(
      <ProvenanceFieldSection layer="enrichment" title="External Enrichment">
        <p>Field content</p>
      </ProvenanceFieldSection>
    );
    expect(screen.getByText("Enriched")).toBeTruthy();
    expect(screen.getByText("External Enrichment")).toBeTruthy();
    expect(screen.getByText("Field content")).toBeTruthy();
  });

  it("renders all four layers", () => {
    const layers = ["source", "enrichment", "canonical", "authority"] as const;
    for (const layer of layers) {
      const { unmount } = render(
        <ProvenanceFieldSection layer={layer} title={`${layer} section`}>
          <span>ok</span>
        </ProvenanceFieldSection>
      );
      unmount();
    }
  });
});
