# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ukip.engine.v1 import engine_pb2 as ukip_dot_engine_dot_v1_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ukip/engine/v1/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSync = channel.unary_unary(
                '/ukip.engine.v1.Engine/ProcessSync',
                request_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.SerializeToString,
                response_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.ProcessAsync = channel.unary_unary(
                '/ukip.engine.v1.Engine/ProcessAsync',
                request_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.SerializeToString,
                response_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobAccepted.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/ukip.engine.v1.Engine/GetJobStatus',
                request_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.StreamProgress = channel.unary_stream(
                '/ukip.engine.v1.Engine/StreamProgress',
                request_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProgressEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ukip.engine.v1.Engine/Health',
                request_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
                _registered_method=True)


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSync,
                    request_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.FromString,
                    response_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessResponse.SerializeToString,
            ),
            'ProcessAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAsync,
                    request_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.FromString,
                    response_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobAccepted.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.FromString,
                    response_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusResponse.SerializeToString,
            ),
            'StreamProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProgress,
                    request_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.FromString,
                    response_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.ProgressEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ukip_dot_engine_dot_v1_dot_engine__pb2.HealthRequest.FromString,
                    response_serializer=ukip_dot_engine_dot_v1_dot_engine__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ukip.engine.v1.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ukip.engine.v1.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ukip.engine.v1.Engine/ProcessSync',
            ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.SerializeToString,
            ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ukip.engine.v1.Engine/ProcessAsync',
            ukip_dot_engine_dot_v1_dot_engine__pb2.ProcessRequest.SerializeToString,
            ukip_dot_engine_dot_v1_dot_engine__pb2.JobAccepted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ukip.engine.v1.Engine/GetJobStatus',
            ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.SerializeToString,
            ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ukip.engine.v1.Engine/StreamProgress',
            ukip_dot_engine_dot_v1_dot_engine__pb2.JobStatusRequest.SerializeToString,
            ukip_dot_engine_dot_v1_dot_engine__pb2.ProgressEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ukip.engine.v1.Engine/Health',
            ukip_dot_engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
            ukip_dot_engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
